name: Cross-Platform Build

on:
  push:
    branches: [ main, develop/* ]
  pull_request:
    branches: [ main, develop/* ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@v3.27.0

      - name: Set up cross-compilation (Linux only)
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          if [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            cmake .. -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "x86_64" ]; then
            cmake ..
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          cmake .. -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake ..
          fi

      - name: Build
        run: |
          cd build
          cmake --build .
