name: Deploy to GitHub Pages (Emscripten)

on:
  push:
    branches: [ main, develop/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: 4.0.15

      - name: Build with emcmake/emmake
        run: |
          mkdir build
          cd build
          emcmake cmake ..
          emmake make

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4